### ISSUE TITLE
iohk-nix/haskell-nix-crypto overlay

### ISSUE THREAD

**Issue by GeorgeFlerovsky** [mlabs-haskell/uplc-benchmark#17]
https://github.com/mlabs-haskell/uplc-benchmark/blob/c1f3f1209427665e48e70428422829f03ce48de7/nix/haskell/lib.nix#L12

FYI `iohk-nix` has a `haskell-nix-crypto` overlay that you may want to include after `iohk-nix/crypto` overlay:

https://github.com/input-output-hk/iohk-nix/blob/master/overlays/haskell-nix-crypto/default.nix

**Comment by t4ccer** [comment]
I'm not really sure what that is but nix setup is moved to https://github.com/mlabs-haskell/simple-haskell-nix and I think it still works without it, I'll look into it more if something breaks
